language: c

sudo: false

notifications:
  email: false

addons:
  apt:
    packages:
    - libgtk2.0-dev
    - libxcursor1
    # - libgl1-mesa-glx
    # - libegl1-mesa
    # - libxrandr2
    # - libxss1
    # - libxcursor1
    # - libxcomposite1
    # - libasound2
    # - libxi6
    # - libxtst6
    # - libnss3
    # - libxslt1.1

env:
  global:
    - COMMAND="pytest glue_vispy_viewers --cov glue_vispy_viewers"
    - SETUP_XVFB=True
    - CONDA_CHANNELS="glueviz"
    - CONDA_DEPENDENCIES="glueviz mock pyopengl pyqt pytest-cov qtpy scipy nomkl"
    - CONDA_CHANNEL_PRIORITY=True
    - PIP_DEPENDENCIES="pytest-faulthandler pytest-qt objgraph"
  matrix:
    - PYTHON_VERSION=2.7 CONDA_CHANNELS="glueviz/label/dev"

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - if [[ $COMMAND == pytest* ]]; then pip install coveralls; fi

script:
  #- python test.py
  - $COMMAND

after_success:
  - if [[ $COMMAND == pytest* ]]; then coveralls; fi
